### PR TITLE
Fix availability classes

### LINKED ISSUE #1: Fix availability classes
@KateEHowlett Here's my suggested fix for the availability classes: https://codepen.io/kieranbarker/pen/jOXrvKe

Each player's state looks like this:

```js
{
	name: "Kate",
	availability: {
		monday: "unknown",
		tuesday: "unknown",
		wednesday: "unknown",
		thursday: "unknown",
		friday: "unknown",
		saturday: "unknown",
		sunday: "unknown"
	}
}
```

The value of `player.availability[day]` can be `"available"`, `"busy"`, `"tentative"`, `"session"`, or `"unknown"`.

The correct class is toggled with a [computed property name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names) of `[player.availability[day]]`:

```vue
<div
	v-for="(availability, day) in player.availability"
	:class="{ [availability]: true }"
>
```

And each `<select>` menu is modelled on `player.availability[day]`:

```vue
<select v-model="player.availability[day]">
	<option value="unknown"></option>
	<option>available</option>
	<option>busy</option>
	<option>tentative</option>
	<option>session</option>
</select>
```

---

I would have raised this under [Discussions](https://docs.github.com/en/discussions) but I think you might need to enable it for this repository.

### PR DESCRIPTION
**Pull request by kieranbarker**
This pull request fixes the issue you were having when trying to toggle the "availability" classes.

Fixes #1.

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -1,274 +1,160 @@
...
+        class="submitButton"
+        aria-controls="availability"
+        :aria-expanded="checkSchedule ? 'true' : 'false'"
+        v-on:click="checkSchedule = true"
+      >
+        Check Availability
+      </button>
+      <div id="availability" v-show="checkSchedule">
+        <div class="displayPlayers" v-for="player in players" :key="player.id">
+          <div style="text-align: center">{{ player.name }}</div>
```
Comment (kieranbarker) [inline src/App.vue:144]: You may want to make a proper class for this rather than using an inline style. I did it in the interest of speed.
